/* 2 chars operators */
yy(TK_OP_INC,       "++")
yy(TK_OP_DEC,       "--")
yy(TK_OP_LAND,      "&&")
yy(TK_OP_LOR,       "||")
yy(TK_OP_EQ,        "==")
yy(TK_OP_NEQ,       "!=")
yy(TK_OP_LE,        "<=")
yy(TK_OP_GE,        ">=")
/* single char operators */
xx(TK_OP_ADD,       '+')
xx(TK_OP_DEL,       '-')
xx(TK_OP_MUL,       '*')
xx(TK_OP_DIV,       '/')
xx(TK_OP_NOT,       '!')
xx(TK_OP_BAND,      '&')
xx(TK_OP_BOR,       '|')
xx(TK_OP_MOD,       '%')
xx(TK_OP_ASSIGN,    '=')
xx(TK_OP_LT,        '<')
xx(TK_OP_GT,        '>')
/* delimiers */
zz(TK_DELIMITER,    '[')
zz(TK_DELIMITER,    ']')
zz(TK_DELIMITER,    '(')
zz(TK_DELIMITER,    ')')
zz(TK_DELIMITER,    '{')
zz(TK_DELIMITER,    '}')
zz(TK_DELIMITER,    ';')
zz(TK_DELIMITER,    ',')